image: python:2.7

before_script:
# - apt-get update -qy
# - apt-get install -y python-dev python-pip
  - pip install -U pytest
  - which python
  - python --version
  - which pytest
  - pytest --version
  - python -c"print( 'hello => {}'.format( 1+2 ))"

testy:
  script:
    - pytest

